### ISSUE TITLE
Need to describe plugins and extensions + emphasize local mkdocs testing

### ISSUE THREAD

**Issue by felker** [argonne-lcf/user-guides#172]
We are installing and enabling a lot of nice markup extensions, etc:
```
  features:
    - tabs
    - instant
    - search.highlight
    - search.suggest
...
markdown_extensions:
  - footnotes
  - admonition
  - codehilite
  - tables
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
...
plugins:
  - include-markdown
  - codeinclude:
      title_mode: pymdownx.tabbed
  - search:
      lang: en
```
But they are not widely used in our .md docs. Many of them (e.g. ` pymdownx.tabbed`, `footnotes`, ` pymdownx.details`, codeinclude) should be used more widely, since they improve readability a lot over vanilla Markdown:
- https://docs.alcf.anl.gov/polaris/data-science-workflows/frameworks/deepspeed/
- https://docs.alcf.anl.gov/running-jobs/example-job-scripts/

We should maybe add a section to our README.md for contributors and authors that highlights some of the simple plugins, examples, and how to use them (and how to add new plugins to the repo?). Also following https://github.com/argonne-lcf/user-guides/issues/144, we should doubly emphasize the importance of deploying and previewing Mkdocs locally instead of using a standalone Markdown GUI editor.
