### ISSUE TITLE
Upgrade to pymdownx's new Blocks API 

### ISSUE THREAD

**Issue by felker** [argonne-lcf/user-guides#609]
Mentioned in https://github.com/argonne-lcf/user-guides/pull/601#issuecomment-2584731271

`pymdownx` introduced a new Blocks API as experimental in [v9.10 (2023-03-05)](https://github.com/facelessuser/pymdown-extensions/releases/tag/9.10) and moved it out of beta in [10.12 (2024-10-28)
](https://github.com/facelessuser/pymdown-extensions/releases/tag/10.12), while marking some of the older API's extensions (Details, Tabbed) as "legacy". There are a handful of advantages to the new API, but the chief [benefits](https://facelessuser.github.io/pymdown-extensions/extensions/blocks/) are that 1) it is more extendable, and 2) whitespace indentation is no longer necessary when writing them, especially helpful for nested blocks. 

The first step would be to modify `mkdocs.yml`, i.e. 
https://github.com/argonne-lcf/user-guides/blob/03b4d6ce98294a993d37e5c49667dd077e394294/mkdocs.yml#L322-L351
would be changed to 
```yaml
 markdown_extensions: 
   - footnotes 
   - codehilite 
   - tables 
   - attr_list 
   - md_in_html 
   - def_list 
   - pymdownx.critic 
   - pymdownx.inlinehilite 
   - pymdownx.keys 
   - pymdownx.caret 
   - pymdownx.mark 
   - pymdownx.tilde 
   - pymdownx.snippets: 
       base_path: ["."]  # for root of repo, default since that is where mkdocs.yml is 
       # base_path: ["docs"] 
       dedent_subsections: True  # experimental; new in 9.10 (2023-03-05) 
       check_paths: True 
       url_download: True 
   - pymdownx.superfences 
   - pymdownx.inlinehilite 
   - pymdownx.highlight: 
       use_pygments: true 
       anchor_linenums: true 
   - pymdownx.tasklist: 
       custom_checkbox: true 
   - pymdownx.blocks
   #- pymdownx.blocks.admonition
   #- pymdownx.blocks.caption
   #- pymdownx.blocks.definition
   #- pymdownx.blocks.details
   #- pymdownx.blocks.html
   - pymdownx.blocks.tab
       alternate_style: true 

```

- [ ] Change `mkdown.yml` extensions as above
- [ ] Perform bulk replacement of `!!!` Admonitions and `???` Details fence syntax with `///`
- [ ] Double check that this new `pymdownx` API remains fully compatible with `mkdocs-material`
- [ ] Try new / create ALCF-customized extension functionality enabled under the new API
